# Generated by Django 2.2.5 on 2021-02-16 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_name', models.CharField(default='group_name_d', max_length=20)),
                ('group_img', models.ImageField(blank=True, upload_to='group_image/')),
                ('group_code', models.CharField(default='default', max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=50)),
                ('user_name', models.CharField(max_length=20)),
                ('user_pw1', models.CharField(max_length=20)),
                ('user_pw2', models.CharField(max_length=20)),
                ('user_birth', models.DateField(verbose_name='date_published')),
                ('user_status', models.BooleanField(default=False)),
                ('group_code', models.ForeignKey(blank=True, db_column='group_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Group')),
            ],
        ),
    ]
